// <auto-generated />
using System;
using HealthGroceryListPlanner.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthGroceryListPlanner.Web.Migrations
{
    [DbContext(typeof(GroceryContext))]
    [Migration("20260304001603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/vegetables.jpg",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/fruits.jpg",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/protein.jpg",
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/dairy.jpg",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/grains.jpg",
                            Name = "Whole Grains"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/nuts.jpg",
                            Name = "Nuts & Seeds"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/fats.jpg",
                            Name = "Healthy Fats"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/beverages.jpg",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Carrot",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 1,
                            Emoji = "🥔",
                            IsPurchased = false,
                            Name = "Potato",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 1,
                            Emoji = "🍅",
                            IsPurchased = false,
                            Name = "Tomato",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 1,
                            Emoji = "🥒",
                            IsPurchased = false,
                            Name = "Cucumber",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 205,
                            CategoryId = 1,
                            Emoji = "🧅",
                            IsPurchased = false,
                            Name = "Onion",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 206,
                            CategoryId = 1,
                            Emoji = "🧄",
                            IsPurchased = false,
                            Name = "Garlic",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 207,
                            CategoryId = 1,
                            Emoji = "🫑",
                            IsPurchased = false,
                            Name = "Bell Pepper",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 208,
                            CategoryId = 1,
                            Emoji = "🥦",
                            IsPurchased = false,
                            Name = "Broccoli",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 209,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Cauliflower",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 210,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Spinach",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 211,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Lettuce",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 212,
                            CategoryId = 1,
                            Emoji = "🥒",
                            IsPurchased = false,
                            Name = "Zucchini",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 213,
                            CategoryId = 1,
                            Emoji = "🍆",
                            IsPurchased = false,
                            Name = "Eggplant",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 214,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Cabbage",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 215,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Red Cabbage",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 216,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Brussels Sprouts",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 217,
                            CategoryId = 1,
                            Emoji = "🫛",
                            IsPurchased = false,
                            Name = "Green Beans",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 218,
                            CategoryId = 1,
                            Emoji = "🫛",
                            IsPurchased = false,
                            Name = "Peas",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 219,
                            CategoryId = 1,
                            Emoji = "🌽",
                            IsPurchased = false,
                            Name = "Corn",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 220,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Asparagus",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 221,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Celery",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 222,
                            CategoryId = 1,
                            Emoji = "🍄",
                            IsPurchased = false,
                            Name = "Mushrooms",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 223,
                            CategoryId = 1,
                            Emoji = "🍠",
                            IsPurchased = false,
                            Name = "Sweet Potato",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 224,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Radish",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 225,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Beetroot",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 226,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Kale",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 227,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Arugula",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 228,
                            CategoryId = 1,
                            Emoji = "🧅",
                            IsPurchased = false,
                            Name = "Leek",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 229,
                            CategoryId = 1,
                            Emoji = "🎃",
                            IsPurchased = false,
                            Name = "Pumpkin",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 230,
                            CategoryId = 1,
                            Emoji = "🎃",
                            IsPurchased = false,
                            Name = "Butternut Squash",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 231,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Turnip",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 232,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Parsnip",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 233,
                            CategoryId = 1,
                            Emoji = "🥬",
                            IsPurchased = false,
                            Name = "Okra",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 234,
                            CategoryId = 1,
                            Emoji = "🌶️",
                            IsPurchased = false,
                            Name = "Jalapeño",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 235,
                            CategoryId = 1,
                            Emoji = "🥑",
                            IsPurchased = false,
                            Name = "Avocado",
                            Quantity = 1m,
                            Unit = 0
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Product", b =>
                {
                    b.HasOne("HealthGroceryListPlanner.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthGroceryListPlanner.Web.Models.ShoppingList", null)
                        .WithMany("Products")
                        .HasForeignKey("ShoppingListId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.ShoppingList", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
