// <auto-generated />
using System;
using HealthGroceryListPlanner.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthGroceryListPlanner.Web.Migrations
{
    [DbContext(typeof(GroceryContext))]
    [Migration("20260304222249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/vegetables.jpg",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/fruits.jpg",
                            Name = "Fruits and Berries"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/protein.jpg",
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/dairy.jpg",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/grains.jpg",
                            Name = "Whole Grains"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/nuts.jpg",
                            Name = "Nuts & Seeds"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/fats.jpg",
                            Name = "Healthy Fats"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/beverages.jpg",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsPurchased = false,
                            Name = "Carrot",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 1,
                            Emoji = "🥔",
                            IsPurchased = false,
                            Name = "Potato",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 1,
                            Emoji = "🍅",
                            IsPurchased = false,
                            Name = "Tomato",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 1,
                            Emoji = "🥒",
                            IsPurchased = false,
                            Name = "Cucumber",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 205,
                            CategoryId = 1,
                            Emoji = "🧅",
                            IsPurchased = false,
                            Name = "Onion",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 206,
                            CategoryId = 1,
                            Emoji = "🧄",
                            IsPurchased = false,
                            Name = "Garlic",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 207,
                            CategoryId = 1,
                            Emoji = "🍆",
                            IsPurchased = false,
                            Name = "Eggplant",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 208,
                            CategoryId = 1,
                            Emoji = "🌽",
                            IsPurchased = false,
                            Name = "Corn",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 2,
                            Emoji = "🍎",
                            IsPurchased = false,
                            Name = "Apple",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 2,
                            Emoji = "🍌",
                            IsPurchased = false,
                            Name = "Banana",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 303,
                            CategoryId = 2,
                            Emoji = "🍊",
                            IsPurchased = false,
                            Name = "Orange",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 304,
                            CategoryId = 2,
                            Emoji = "🍓",
                            IsPurchased = false,
                            Name = "Strawberry",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 305,
                            CategoryId = 2,
                            Emoji = "🍇",
                            IsPurchased = false,
                            Name = "Grapes",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 401,
                            CategoryId = 3,
                            Emoji = "🍗",
                            IsPurchased = false,
                            Name = "Chicken Breast",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 402,
                            CategoryId = 3,
                            Emoji = "🐟",
                            IsPurchased = false,
                            Name = "Salmon",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 403,
                            CategoryId = 3,
                            Emoji = "🥚",
                            IsPurchased = false,
                            Name = "Eggs",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 404,
                            CategoryId = 3,
                            Emoji = "🧊",
                            IsPurchased = false,
                            Name = "Tofu",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 405,
                            CategoryId = 3,
                            Emoji = "🫘",
                            IsPurchased = false,
                            Name = "Beans",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 501,
                            CategoryId = 4,
                            Emoji = "🥛",
                            IsPurchased = false,
                            Name = "Milk",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 502,
                            CategoryId = 4,
                            Emoji = "🧀",
                            IsPurchased = false,
                            Name = "Cheese",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 503,
                            CategoryId = 4,
                            Emoji = "🥣",
                            IsPurchased = false,
                            Name = "Yogurt",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 504,
                            CategoryId = 4,
                            Emoji = "🧈",
                            IsPurchased = false,
                            Name = "Butter",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 505,
                            CategoryId = 4,
                            Emoji = "🥛",
                            IsPurchased = false,
                            Name = "Cottage Cheese",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 601,
                            CategoryId = 5,
                            Emoji = "🍚",
                            IsPurchased = false,
                            Name = "Brown Rice",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 602,
                            CategoryId = 5,
                            Emoji = "🥣",
                            IsPurchased = false,
                            Name = "Oats",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 603,
                            CategoryId = 5,
                            Emoji = "🍚",
                            IsPurchased = false,
                            Name = "Quinoa",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 604,
                            CategoryId = 5,
                            Emoji = "🍞",
                            IsPurchased = false,
                            Name = "Whole Wheat Bread",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 605,
                            CategoryId = 5,
                            Emoji = "🌾",
                            IsPurchased = false,
                            Name = "Barley",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 701,
                            CategoryId = 6,
                            Emoji = "🌰",
                            IsPurchased = false,
                            Name = "Almonds",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 702,
                            CategoryId = 6,
                            Emoji = "🌰",
                            IsPurchased = false,
                            Name = "Walnuts",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 703,
                            CategoryId = 6,
                            Emoji = "🥜",
                            IsPurchased = false,
                            Name = "Cashews",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 704,
                            CategoryId = 6,
                            Emoji = "🌱",
                            IsPurchased = false,
                            Name = "Chia Seeds",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 705,
                            CategoryId = 6,
                            Emoji = "🌱",
                            IsPurchased = false,
                            Name = "Flax Seeds",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 801,
                            CategoryId = 7,
                            Emoji = "🥑",
                            IsPurchased = false,
                            Name = "Avocado",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 802,
                            CategoryId = 7,
                            Emoji = "🫒",
                            IsPurchased = false,
                            Name = "Olive Oil",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 803,
                            CategoryId = 7,
                            Emoji = "🥥",
                            IsPurchased = false,
                            Name = "Coconut Oil",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 804,
                            CategoryId = 7,
                            Emoji = "🍫",
                            IsPurchased = false,
                            Name = "Dark Chocolate",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 805,
                            CategoryId = 7,
                            Emoji = "🥜",
                            IsPurchased = false,
                            Name = "Peanut Butter",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 901,
                            CategoryId = 8,
                            Emoji = "☕",
                            IsPurchased = false,
                            Name = "Coffee",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 902,
                            CategoryId = 8,
                            Emoji = "🍵",
                            IsPurchased = false,
                            Name = "Green Tea",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 903,
                            CategoryId = 8,
                            Emoji = "🍵",
                            IsPurchased = false,
                            Name = "Black Tea",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 904,
                            CategoryId = 8,
                            Emoji = "🍊",
                            IsPurchased = false,
                            Name = "Orange Juice",
                            Quantity = 1m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 905,
                            CategoryId = 8,
                            Emoji = "🥤",
                            IsPurchased = false,
                            Name = "Smoothie",
                            Quantity = 1m,
                            Unit = 0
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Product", b =>
                {
                    b.HasOne("HealthGroceryListPlanner.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthGroceryListPlanner.Web.Models.ShoppingList", null)
                        .WithMany("Products")
                        .HasForeignKey("ShoppingListId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Web.Models.ShoppingList", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
