// <auto-generated />
using System;
using HealthGroceryListPlanner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthGroceryListPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(GroceryContext))]
    partial class GroceryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emoji = "",
                            ImageUrl = "/images/vegetables.jpg",
                            IsGlobal = true,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Emoji = "",
                            ImageUrl = "/images/fruits.jpg",
                            IsGlobal = true,
                            Name = "Fruits and Berries"
                        },
                        new
                        {
                            Id = 3,
                            Emoji = "",
                            ImageUrl = "/images/protein.jpg",
                            IsGlobal = true,
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 4,
                            Emoji = "",
                            ImageUrl = "/images/dairy.jpg",
                            IsGlobal = true,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            Emoji = "",
                            ImageUrl = "/images/grains.jpg",
                            IsGlobal = true,
                            Name = "Whole Grains"
                        },
                        new
                        {
                            Id = 6,
                            Emoji = "",
                            ImageUrl = "/images/nuts.jpg",
                            IsGlobal = true,
                            Name = "Nuts & Seeds"
                        },
                        new
                        {
                            Id = 7,
                            Emoji = "",
                            ImageUrl = "/images/fats.jpg",
                            IsGlobal = true,
                            Name = "Healthy Fats"
                        },
                        new
                        {
                            Id = 8,
                            Emoji = "",
                            ImageUrl = "/images/beverages.jpg",
                            IsGlobal = true,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShoppingListId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            CategoryId = 1,
                            Emoji = "🥕",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Carrot",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 1,
                            Emoji = "🥔",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Potato",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 1,
                            Emoji = "🍅",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Tomato",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 2,
                            Emoji = "🍎",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Apple",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 2,
                            Emoji = "🍌",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Banana",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 401,
                            CategoryId = 3,
                            Emoji = "🍗",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Chicken Breast",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 402,
                            CategoryId = 3,
                            Emoji = "🐟",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Salmon",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 501,
                            CategoryId = 4,
                            Emoji = "🥛",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Milk",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 601,
                            CategoryId = 5,
                            Emoji = "🥣",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Oats",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 701,
                            CategoryId = 6,
                            Emoji = "🌰",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Almonds",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 801,
                            CategoryId = 7,
                            Emoji = "🥑",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Avocado",
                            Quantity = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 901,
                            CategoryId = 8,
                            Emoji = "☕",
                            IsGlobal = true,
                            IsPurchased = false,
                            Name = "Coffee",
                            Quantity = 1,
                            Unit = 0
                        });
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.Category", b =>
                {
                    b.HasOne("HealthGroceryListPlanner.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.Product", b =>
                {
                    b.HasOne("HealthGroceryListPlanner.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthGroceryListPlanner.Domain.Models.ShoppingList", "ShoppingList")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthGroceryListPlanner.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ShoppingList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.ShoppingList", b =>
                {
                    b.HasOne("HealthGroceryListPlanner.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HealthGroceryListPlanner.Domain.Models.ShoppingList", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
